--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item (
    id bigint NOT NULL,
    calories integer NOT NULL,
    category character varying(255),
    description character varying(255),
    image_url character varying(255),
    is_best_seller boolean,
    name character varying(255),
    price integer NOT NULL,
    CONSTRAINT item_category_check CHECK (((category)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'SOUP'::character varying, 'SUSHI'::character varying, 'DRINK'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.item OWNER TO postgres;

--
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    image_url character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    restaurant_name character varying(255)
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item (id, calories, category, description, image_url, is_best_seller, name, price) FROM stdin;
31	150	DRINK	Chilled espresso with milk	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	t	Iced Latte	16
32	180	DRINK	Spinach, banana, mango	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	f	Green Smoothie	20
33	120	DRINK	Espresso with foam	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	t	Cappuccino	14
34	180	DRINK	Matcha with steamed milk	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	f	Matcha Latte	18
35	160	DRINK	Freshly squeezed	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	t	Orange Juice	12
36	300	DRINK	Strawberries & ice cream	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	f	Strawberry Milkshake	22
37	30	DRINK	Single strong shot	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	t	Espresso	10
38	140	DRINK	Lemons, sugar, mint	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	f	Lemonade	12
39	210	DRINK	Mango, yogurt, ice	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	t	Mango Smoothie	18
40	280	DRINK	Cocoa with cream	https://media.istockphoto.com/id/504333530/photo/many-cups-of-coffee-on-wooden-table.jpg?s=612x612&w=0&k=20&c=Ea9OjNqOmC5AzfPXoTvu7gFtoj4a9-1r5uuhgmCV3Bk=	f	Hot Chocolate	20
11	210	SOUP	Creamy tomato soup with herbs	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Tomato Soup	15
12	280	SOUP	Homestyle with fresh vegetables	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	t	Chicken Noodle Soup	22
13	120	SOUP	Miso broth with tofu & seaweed	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Miso Soup	12
14	230	SOUP	Hearty lentils, carrots, spices	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	t	Lentil Soup	18
15	330	SOUP	Creamy chowder with potatoes	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Clam Chowder	24
21	190	SUSHI	Fresh salmon over rice	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	t	Salmon Nigiri	35
22	240	SUSHI	Crab, avocado, cucumber	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	f	California Roll	28
23	210	SUSHI	Fresh tuna maki	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	t	Tuna Roll	30
24	260	SUSHI	Crispy shrimp, avocado	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	f	Shrimp Tempura Roll	32
25	340	SUSHI	Eel, cucumber, avocado top	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	t	Dragon Roll	38
26	190	SUSHI	Cucumber, avocado, carrot	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	f	Vegetable Roll	22
27	250	SUSHI	Tuna with spicy mayo	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	t	Spicy Tuna Roll	32
41	600	OTHER	Rich chocolate ganache slice	https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg	t	Chocolate Cake	30
42	400	OTHER	Crispy salted fries	https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg	f	French Fries	12
43	550	OTHER	NY-style with strawberry sauce	https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg	t	Cheesecake	28
44	450	OTHER	Battered rings with dip	https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg	f	Onion Rings	14
45	470	OTHER	Vanilla, chocolate, nuts	https://cdn.pixabay.com/photo/2017/01/11/11/33/cake-1971552_1280.jpg	t	Ice Cream Sundae	25
46	310	OTHER	Toasted garlic butter bread	https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg	f	Garlic Bread	10
1	520	BREAKFAST	Fluffy pancakes with butter and syrup	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	t	Pancake Stack	25
2	340	BREAKFAST	Sourdough topped with smashed avocado	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	f	Avocado Toast	18
3	430	BREAKFAST	Three-egg omelette with veggies & cheese	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	t	Omelette Deluxe	22
4	480	BREAKFAST	Crispy waffles with berries	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	f	Classic Waffles	26
5	500	BREAKFAST	Poached eggs, muffin, hollandaise	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	t	Eggs Benedict	28
6	320	BREAKFAST	Yogurt, granola, honey, fruits	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	f	Granola Bowl	20
7	540	BREAKFAST	Tortilla with eggs, cheese, sausage	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	t	Breakfast Burrito	28
8	270	BREAKFAST	Buttery flaky pastry	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	f	Butter Croissant	14
9	460	BREAKFAST	Golden toast with cinnamon sugar	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	t	French Toast	24
10	350	BREAKFAST	Toasted bagel with cream cheese	https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_1280.jpg	f	Bagel & Cream Cheese	15
16	280	SOUP	Roasted pumpkin with nutmeg	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Pumpkin Soup	20
17	380	SOUP	Slow-cooked beef & vegetables	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	t	Beef Stew	30
18	220	SOUP	Tofu, mushrooms, chili, vinegar	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Hot & Sour Soup	18
19	330	SOUP	Creamy cheddar & broccoli	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	t	Broccoli Cheddar	24
20	360	SOUP	Rich soup with shrimp & crab	https://www.thespruceeats.com/thmb/lko3xX8clhOrC894t9Drb6MoiX0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-and-hearty-vegetable-soup-99538-hero-01-1d3b936ff03144af95ddca7640259c11.jpg	f	Seafood Bisque	34
28	330	SUSHI	Crab topped with assorted fish	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	f	Rainbow Roll	40
29	300	SUSHI	Grilled eel with glaze	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	t	Unagi Nigiri	36
30	420	SUSHI	Udon with shrimp tempura	https://as2.ftcdn.net/v2/jpg/01/60/77/63/1000_F_160776300_2VfVdDN1wC8JuawVMiMOte0vSOF8xVxp.jpg	f	Tempura Udon	42
47	490	OTHER	Coffee-soaked classic dessert	https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg	t	Tiramisu	30
48	520	OTHER	Chips with cheese & salsa	https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg	f	Nachos	26
49	440	OTHER	Fried cheese sticks	https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg	t	Mozzarella Sticks	22
50	390	OTHER	Cinnamon sugar pastries	https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141352.jpg	f	Churros	18
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location (id, image_url, latitude, longitude, restaurant_name) FROM stdin;
1	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.7257	46.6696	Cheko - Al Olaya
2	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.7406	46.6704	Cheko - King Fahd District
3	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.6643	46.7354	Cheko - Al Malaz
4	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.7917	46.8377	Cheko - Al Maizalah
5	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.5098	46.6169	Cheko - Dirab
6	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0gVhtTKXI8LPqCDMDYpyH3oJVNMvrZsbJuQ&s	24.75661	46.590327	Cheko - Hittin
\.


--
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_id_seq', 50, true);


--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.location_id_seq', 6, true);


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

